In [185]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [186]:
train_data = pd.read_csv('Datasets/dataset/train.csv')

In [187]:
train_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1  TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2  BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3  WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4  JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0      Lillyann              Yes          Fashion      1      68   
1         Klynn              Yes          Fashion      0      51   
2         Ridge              Yes       Child_care      0      10   
3         Abran              Yes      Educational      2      48   
4        Dustyn              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917824  
4     906.553935

In [188]:
train_data.isnull().sum()

Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

In [189]:
train_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1  TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2  BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3  WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4  JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0      Lillyann              Yes          Fashion      1      68   
1         Klynn              Yes          Fashion      0      51   
2         Ridge              Yes       Child_care      0      10   
3         Abran              Yes      Educational      2      48   
4        Dustyn              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917824  
4     906.553935

In [190]:
'''train_data['Stall_no'] = train_data['Stall_no'].fillna(train_data['Stall_no'].mean())
train_data['Discount_avail'] = train_data['Discount_avail'].fillna(train_data['Discount_avail'].mean())
train_data['charges_1'] = train_data['charges_1'].fillna(train_data['charges_1'].mean())
train_data['charges_2 (%)'] = train_data['charges_2 (%)'].fillna(train_data['charges_2 (%)'].mean())
train_data['Minimum_price'] = train_data['Minimum_price'].fillna(train_data['Minimum_price'].mean())
train_data['Maximum_price'] = train_data['Maximum_price'].fillna(train_data['Maximum_price'].mean())
train_data['Selling_Price'] = train_data['Selling_Price'].fillna(train_data['Selling_Price'].mean())'''

"train_data['Stall_no'] = train_data['Stall_no'].fillna(train_data['Stall_no'].mean())\ntrain_data['Discount_avail'] = train_data['Discount_avail'].fillna(train_data['Discount_avail'].mean())\ntrain_data['charges_1'] = train_data['charges_1'].fillna(train_data['charges_1'].mean())\ntrain_data['charges_2 (%)'] = train_data['charges_2 (%)'].fillna(train_data['charges_2 (%)'].mean())\ntrain_data['Minimum_price'] = train_data['Minimum_price'].fillna(train_data['Minimum_price'].mean())\ntrain_data['Maximum_price'] = train_data['Maximum_price'].fillna(train_data['Maximum_price'].mean())\ntrain_data['Selling_Price'] = train_data['Selling_Price'].fillna(train_data['Selling_Price'].mean())"

In [191]:
#train_data.isnull().sum()

In [192]:
train_data = train_data.dropna()

In [193]:
test_data = pd.read_csv('Datasets/dataset/test.csv')

In [194]:
test_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  SCHE4YSTDVPVZVXW      39.0  2016-01-13 07:45:08.000              205   
1  ACCEGCATKHNRXUHW      49.0  2015-08-23 20:37:05.000                3   
2  NKCE6GJ5XVJDXNNZ       1.0  2015-11-14 18:12:39.000              183   
3  NKCEB8BK3ZXDHDHM       8.0  2015-11-21 04:56:19.000              358   
4  TOPEFDXSAHRNPF94      33.0  2015-05-06 15:09:46.000              167   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0        Ivanka              No           Fashion      0      90   
1         Isaak              Yes          Fashion      0      87   
2      Analiese              No        Technology      2      55   
3         Rusty              Yes       Child_care      3      86   
4        Eloise              No        Technology      0      27   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  
0               0      380.0           16.0         2576.0           3340  
1               0      393.0           16.0         1202.0           1955  
2               0      493.0            9.0         7175.0          15715  
3               0      303.0           16.0         5404.0          13078  
4               0      567.0           16.0         4069.0           6244

In [195]:
test_data.isna().sum()

Product_id           0
Stall_no             1
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2 (%)        5
Minimum_price       14
Maximum_price        0
dtype: int64

In [196]:
test_data['Stall_no'] = test_data['Stall_no'].fillna(test_data['Stall_no'].mean())
test_data['Discount_avail'] = test_data['Discount_avail'].fillna(test_data['Discount_avail'].mean())
test_data['charges_1'] = test_data['charges_1'].fillna(test_data['charges_1'].mean())
test_data['charges_2 (%)'] = test_data['charges_2 (%)'].fillna(test_data['charges_2 (%)'].mean())
test_data['Minimum_price'] = test_data['Minimum_price'].fillna(test_data['Minimum_price'].mean())
test_data['Maximum_price'] = test_data['Maximum_price'].fillna(test_data['Maximum_price'].mean())


In [197]:
test_data.isna().sum()

Product_id           0
Stall_no             0
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1            0
charges_2 (%)        0
Minimum_price        0
Maximum_price        0
dtype: int64

In [198]:
train_id = train_data['Product_id']

In [199]:
train_id.head()

0    BRAE2NF6JA5GUEXG
1    TUNE8SFB6RJN2HSD
2    BRAEAR7WZPQGPBZU
3    WATDZ2ZQ8JPDHCTJ
4    JWSEBUKYQPMBZ3RK
Name: Product_id, dtype: object

In [200]:
test_id = test_data['Product_id']

In [201]:
test_id.head()

0    SCHE4YSTDVPVZVXW
1    ACCEGCATKHNRXUHW
2    NKCE6GJ5XVJDXNNZ
3    NKCEB8BK3ZXDHDHM
4    TOPEFDXSAHRNPF94
Name: Product_id, dtype: object

In [202]:
x_train = train_data.iloc[:,[5,7,8,9,10,11,12,13]].values
y_train = train_data.iloc[:,14].values

In [203]:
x_test = test_data.iloc[:,[5,7,8,9,10,11,12,13]].values


In [204]:
x_test

array([['No ', 0, 90, ..., 16.0, 2576.0, 3340],
       ['Yes', 0, 87, ..., 16.0, 1202.0, 1955],
       ['No ', 2, 55, ..., 9.0, 7175.0, 15715],
       ...,
       ['Yes', 0, 36, ..., 17.0, 710.0, 10894],
       ['Yes', 0, 63, ..., 15.0, 1477.0, 5165],
       ['No ', 0, 92, ..., 9.0, 5538.0, 7506]], dtype=object)

In [205]:
x_train


array([['Yes', 1, 68, ..., 11.0, 2983.0, 4713.0],
       ['Yes', 0, 51, ..., 12.0, 7495.0, 10352.0],
       ['Yes', 0, 10, ..., 9.0, 5752.0, 7309.0],
       ...,
       ['No ', 3, 29, ..., 3.0, 5303.0, 14614.0],
       ['Yes', 0, 8, ..., 3.0, 4334.0, 5849.0],
       ['Yes', 0, 94, ..., 7.0, 3975.0, 5383.0]], dtype=object)

In [206]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le_train1 = LabelEncoder()
#le_train2 = LabelEncoder()
x_train[:,0] = le_train1.fit_transform(x_train[:,0])
#x_train[:,2] = le_train2.fit_transform(x_train[:,2])

In [207]:
x_train[:5,:]

array([[1, 1, 68, 0.0, 376.0, 11.0, 2983.0, 4713.0],
       [1, 0, 51, 0.0, 397.0, 12.0, 7495.0, 10352.0],
       [1, 0, 10, 0.0, 250.0, 9.0, 5752.0, 7309.0],
       [1, 2, 48, 0.0, 144.0, 13.0, 5090.0, 20814.0],
       [1, 1, 35, 1.0, 211.0, 4.0, 2430.0, 9261.0]], dtype=object)

In [208]:
le_test1 = LabelEncoder()
#le_test2 = LabelEncoder()
x_test[:,0] = le_test1.fit_transform(x_test[:,0])
#x_test[:,2] = le_test2.fit_transform(x_test[:,2])

In [209]:
x_test[:5,:]

array([[0, 0, 90, 0, 380.0, 16.0, 2576.0, 3340],
       [1, 0, 87, 0, 393.0, 16.0, 1202.0, 1955],
       [0, 2, 55, 0, 493.0, 9.0, 7175.0, 15715],
       [1, 3, 86, 0, 303.0, 16.0, 5404.0, 13078],
       [0, 0, 27, 0, 567.0, 16.0, 4069.0, 6244]], dtype=object)

In [210]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train);
x_test = sc.transform(x_test);

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [211]:
x_train

array([[ 8.05259134e-01,  3.31862989e-01,  5.84198521e-01, ...,
         1.91555986e-01, -2.54246809e-01, -4.72609036e-01],
       [ 8.05259134e-01, -6.35234502e-01, -7.39548290e-04, ...,
         4.22940868e-01,  1.78586158e+00,  1.02650052e+00],
       [ 8.05259134e-01, -6.35234502e-01, -1.41147254e+00, ...,
        -2.71213779e-01,  9.97761199e-01,  2.17529002e-01],
       ...,
       [-1.24183627e+00,  2.26605797e+00, -7.57718226e-01, ...,
        -1.65952307e+00,  7.94745093e-01,  2.15953916e+00],
       [ 8.05259134e-01, -6.35234502e-01, -1.48028878e+00, ...,
        -1.65952307e+00,  3.56610113e-01, -1.70607182e-01],
       [ 8.05259134e-01, -6.35234502e-01,  1.47880969e+00, ...,
        -7.33983544e-01,  1.94287659e-01, -2.94491745e-01]])

In [212]:
x_test

array([[-1.24183627, -0.6352345 ,  1.3411772 , ...,  1.3484804 ,
        -0.43827254, -0.83761656],
       [ 0.80525913, -0.6352345 ,  1.23795283, ...,  1.3484804 ,
        -1.05952896, -1.20581424],
       [-1.24183627,  1.29896048,  0.13689294, ..., -0.27121378,
         1.64117304,  2.45223638],
       ...,
       [ 0.80525913, -0.6352345 , -0.51686137, ...,  1.57986528,
        -1.28198758,  1.17058943],
       [ 0.80525913, -0.6352345 ,  0.41215791, ...,  1.11709552,
        -0.93518724, -0.35244633],
       [-1.24183627, -0.6352345 ,  1.40999344, ..., -0.27121378,
         0.90100074,  0.2699008 ]])

In [213]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#from sklearn.ensemble import VotingRegressor
from sklearn import linear_model
from sklearn.svm import LinearSVR
from sklearn.svm import SVR
from sklearn.svm import NuSVR

In [214]:
def find_best_model(X,Y):
    models = {
        'linear_regression' :{
            'model': LinearRegression(),
            'parameters':{
                
            }
        },
        
        'decison_tree_regressor':{
            'model': DecisionTreeRegressor(splitter='best'),
            'parameters' :{
                'max_depth' :[5,10]
            }
        },
        
        'random_forest': {
            'model': RandomForestRegressor(),
            
            'parameters' :{
                'n_estimators': [100]
            }
        },
            'linear_model' :{
                'model' : linear_model.Lasso(),
                'parameters' : {
                    'alpha' : [1]
                }
            
        },
        'ElasticNet' :
        {
            'model' : linear_model.ElasticNet(),
            'parameters':{
                'l1_ratio': [1],
                'alpha' : [1]
            }
        },
        'Ridge' :{
                'model' : linear_model.Ridge(),
                'parameters' : {
                    'alpha' : [1]
                }
            
        },
        'LinSVR' :{
                'model' : LinearSVR(),
                'parameters' : {
                    'epsilon' : [0],
                    'tol':[1e-5]
                }
            
        }
        
    }
    
    scores = []
    cv_shuffle = ShuffleSplit(n_splits=5,test_size= 0.2,random_state=0)
    
    for model_names,model_params in models.items():
        gc = GridSearchCV(model_params['model'],model_params['parameters'],cv = cv_shuffle,return_train_score= False)
        gc.fit(X,Y)
        scores.append({
            'model': model_names,
            'parameters' : gc.best_params_,
            'score' : gc.best_score_
        })
        
    return pd.DataFrame(scores, columns=['model','best_parameters','score']);

find_best_model(x_train, y_train)

model  best_parameters     score
0       linear_regression              NaN  0.904139
1  decison_tree_regressor              NaN  0.962407
2           random_forest              NaN  0.979903
3            linear_model              NaN  0.904144
4              ElasticNet              NaN  0.904144
5                   Ridge              NaN  0.904144
6                  LinSVR              NaN  0.340722

In [274]:
regressor = RandomForestRegressor(n_estimators= 95)
regressor.fit(x_train,y_train);

In [275]:
predictions = regressor.predict(x_test)

In [276]:
regressor.score(x_train,y_train)

0.9970731221820924

In [277]:
predictions = abs(predictions)

In [278]:
predictions.shape

(3430,)

In [36]:
dtr =  DecisionTreeRegressor(splitter = 'best')
dtr.fit(x_train,y_train)
predictions2 = dtr.predict(x_test)
predictions2 = abs(predictions2)
predictions2

array([ 3169.992969,  1946.272125, 12107.327232, ...,  6572.86272 ,
        3334.393216,  1010.981664])

In [257]:
#dtr.score(x_train,y_train)

1.0

In [258]:
'''clf = linear_model.Ridge(alpha = 1)
clf.fit(x_train,y_train)
predictions1 = clf.predict(x_test)'''

In [259]:
#predictions1=abs(predictions1)

In [260]:
#clf.score(x_train,y_train)

0.8843744986919082

In [261]:
'''s_v = SVR(kernel='linear')
s_v.fit(x_train,y_train)
predictions3 = s_v.predict(x_test)
predictions3 = abs(predictions3)
predictions3'''

array([ 3294.6074021 ,  1945.68559566, 11809.51768045, ...,
        5891.8116794 ,  3612.08150704,  3567.34777988])

In [262]:
#s_v.score(x_train,y_train)

0.8452876958195298

In [263]:
test_data.shape

(3430, 14)

In [279]:
data = pd.DataFrame((zip(test_id,predictions)),columns=['Product_id','Selling_Price'])
#data1 = pd.DataFrame((zip(test_id,predictions2)),columns=['Product_id','Selling_Price'])
#data2 = pd.DataFrame((zip(test_id,predictions1)),columns=['Product_id','Selling_Price'])
#data3 = pd.DataFrame((zip(test_id,predictions3)),columns=['Product_id','Selling_Price'])
#data1 = pd.DataFrame((zip(test_id,predictions2)),columns=['Product_id','Selling_Price'])
#data1 = pd.DataFrame((zip(test_id,predictions2)),columns=['Product_id','Selling_Price'])

In [280]:
data.head()

Product_id  Selling_Price
0  SCHE4YSTDVPVZVXW    3261.918502
1  ACCEGCATKHNRXUHW    1949.932263
2  NKCE6GJ5XVJDXNNZ   11810.125083
3  NKCEB8BK3ZXDHDHM    9368.910953
4  TOPEFDXSAHRNPF94    5533.055919

In [281]:
data.to_csv('output94.csv',index= False)

In [203]:
data1.head()

Product_id  Selling_Price
0  SCHE4YSTDVPVZVXW    3178.292375
1  ACCEGCATKHNRXUHW    1946.272125
2  NKCE6GJ5XVJDXNNZ   12451.228848
3  NKCEB8BK3ZXDHDHM    8860.948096
4  TOPEFDXSAHRNPF94    5594.730471

In [142]:
data1.to_csv('output64.csv',index= False)

In [270]:
data2.head()

Product_id  Selling_Price
0  SCHE4YSTDVPVZVXW    3324.297456
1  ACCEGCATKHNRXUHW    1834.743680
2  NKCE6GJ5XVJDXNNZ   11977.080192
3  NKCEB8BK3ZXDHDHM    8860.948096
4  TOPEFDXSAHRNPF94    5631.247872

In [271]:
data2.to_csv('output31.csv',index= False)

In [272]:
data3.head()

Product_id  Selling_Price
0  SCHE4YSTDVPVZVXW    3294.607402
1  ACCEGCATKHNRXUHW    1945.685596
2  NKCE6GJ5XVJDXNNZ   11809.517680
3  NKCEB8BK3ZXDHDHM    9420.948528
4  TOPEFDXSAHRNPF94    5701.146209

In [273]:
data3.to_csv('output32.csv',index = False)